// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0suNP9FuLcWTav_tljr2itq_cleRh8g',
    appId: '1:861154168938:web:97cd8c54a2e1ed95797a13',
    messagingSenderId: '861154168938',
    projectId: 'i-love-my-girlfriend-firebase',
    authDomain: 'i-love-my-girlfriend-firebase.firebaseapp.com',
    storageBucket: 'i-love-my-girlfriend-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARogxC7yYBzA3xhEXXv3jCEFKpxM_CglE',
    appId: '1:861154168938:android:4b1b7a6293d3bd36797a13',
    messagingSenderId: '861154168938',
    projectId: 'i-love-my-girlfriend-firebase',
    storageBucket: 'i-love-my-girlfriend-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5RDKPc1H_5Tc4jKqHIgvbP4C-4OjRczQ',
    appId: '1:861154168938:ios:2ed44fda5a8eb5ab797a13',
    messagingSenderId: '861154168938',
    projectId: 'i-love-my-girlfriend-firebase',
    storageBucket: 'i-love-my-girlfriend-firebase.appspot.com',
    iosBundleId: 'com.example.iLoveMyGirlfriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5RDKPc1H_5Tc4jKqHIgvbP4C-4OjRczQ',
    appId: '1:861154168938:ios:2ed44fda5a8eb5ab797a13',
    messagingSenderId: '861154168938',
    projectId: 'i-love-my-girlfriend-firebase',
    storageBucket: 'i-love-my-girlfriend-firebase.appspot.com',
    iosBundleId: 'com.example.iLoveMyGirlfriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv0suNP9FuLcWTav_tljr2itq_cleRh8g',
    appId: '1:861154168938:web:ebd28c340b77dbd9797a13',
    messagingSenderId: '861154168938',
    projectId: 'i-love-my-girlfriend-firebase',
    authDomain: 'i-love-my-girlfriend-firebase.firebaseapp.com',
    storageBucket: 'i-love-my-girlfriend-firebase.appspot.com',
  );
}
